version: '3.3'
services:

  mongo:
    image: mongo:${MONGO_VERSION}
    deploy:
      placement:
        constraints:
          - node.labels.reliability == high
    volumes:
      - mongo_data:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      prometheus_net:
        aliases:
          - mongo

  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    environment:
      - APP_ENVIRONMENT
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 1s
      resources:
        limits:
          cpus: '0.30'
          memory: 300M
      update_config:
        delay: 10s
        parallelism: 2
        failure_action: rollback
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
    networks:
      - front_net
      - back_net
      - prometheus_net

  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    environment:
      - APP_ENVIRONMENT
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 1s
      resources:
        limits:
          cpus: '0.30'
          memory: 300M
      update_config:
        delay: 10s
        parallelism: 2
        failure_action: rollback
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
    networks:
      - front_net
      - back_net
      - prometheus_net

  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    environment:
      - ENV=${APP_ENVIRONMENT}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 3s
      resources:
        limits:
          cpus: '0.50'
          memory: 150M
      update_config:
        delay: 5s
        parallelism: 1
        failure_action: rollback
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
    ports:
      - "${UI_PORT}:9292/tcp"
    networks:
      - front_net
      - prometheus_net

volumes:
  mongo_data: {}

networks:
  back_net: {}
  front_net: {}
