kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: N/yaN7Tx+ubbwd5UrxjM08tG8hrxbWGkEQf1o15dOeI=
      - identity: {}
